config/routes.rb
Myapp::Application.routes.draw do
    
  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"
    resources :tasks
    resources :part_lists
    
  get "landing_pages/home"
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  

  root :to => 'landing_pages#home'

  

end

app/models/grading.rb
class Grading < ActiveRecord::Base
  belongs_to :task
end

app/models/part_list.rb
class PartList < ActiveRecord::Base
  belongs_to :task
  scope :incomplete,-> {where(complete: false).order(:title)}
  scope :high_priority, -> { where('priority = ?', "high")}
  scope :med_priority, -> { where('priority = ?', "medium")}
  scope :low_priority, -> { where('priority = ?', "low")}
end

app/models/ratings.rb
class Ratings < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :work, presence: true
	validates :course, presence: true
	validates :email, presence: true
	validates :course, length: {within: 5..7}
	formatValidation = /[a-z-]+[\d]+/i
	emailFormatValidation = /[a-z.-]+@[a-z \d .-]+.[a-z]+/i
  validates :course, format: {with: formatValidation}
  validates :email, format: {with: emailFormatValidation}
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def after_sign_in_path_for(user)
  		return landing_pages_home_url
  end

end

app/controllers/gradings_controller.rb
class GradingsController < ApplicationController
    def grading_params
        params.require(:grading).permit(:percent,:importance,:finalgrade,:task)
    end
  
  def index
      @gradings = Grading.all
  end

  def new
      @grading = Grading.new
  end
  
  def create
          @grading = Grading.new(grading_params)
          if @grading.save
              redirect_to gradings_path
              else
              render 'new'
          end
  end

  def edit
  end

  def show
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
    def home
    end
end

app/controllers/part_lists_controller.rb
class PartListsController < ApplicationController
    def part_lists_params
        params.require(:part_list).permit(:title,:complete,:priority,:task_id, :task)
    end
    
    def index
        if current_user
            @part_lists = PartList.incomplete
            @message = ""
        else
            @part_lists = []
            @message = "Can't view/add parts unless signed in"
        end
    end

    def new
        @part_list = PartList.new
    end
    
    def create
        if current_user
            @part_list = PartList.new(part_lists_params)
            if @part_list.save
                redirect_to part_lists_path
            else
                render 'new'
            end
        else
            @message = "Can't view/add parts unless signed in"
            redirect_to part_lists_path
        end
    end
    
    def update
        @part_list = PartList.find(params[:id])
        if @part_list.update_attributes(part_lists_params)
            redirect_to part_list_path(@part_list.id)
            else
            render 'edit'
        end
    end

    def destroy
        @part_list = PartList.find(params[:id])
        @part_list.destroy
        redirect_to part_lists_path
    end


    def edit
        @part_list = PartList.find(params[:id])
    end

    def show
        @part_list = PartList.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def failure
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def task_params
      params.require(:task).permit(:work,:course,:dueday, :email, :user_id)
  end
  

  def show
    @task = Task.find(params[:id])
    if current_user != nil
      if (@task.user_id == current_user.id)
        @name = current_user.name
      else
        @name = "can't show username due to privacy concerns"
      end
    else
      @name = "can't show username due to privacy concerns"
    end
  end
  
  def edit
      @task = Task.find(params[:id])
  end
  
  def new
      @task = Task.new
  end

  def index
    if current_user
      @tasks = Task.where(user_id: current_user)
    else
      @tasks=Task.all
    end
  end

  def update
      @task = Task.find(params[:id])
      if @task.update_attributes(task_params)
          redirect_to task_path(@task.id)
          else
          render 'edit'
      end
  end
  
  def destroy
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path
  end
  
  def create
    @task = Task.new(task_params)
      if @task.save
        Notifications.new_task(@task).deliver
        redirect_to tasks_path
      else
        render 'new'
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gradings_helper.rb
module GradingsHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/part_list_helper.rb
module PartListHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gradings/edit.html.erb
<h1>Gradings#edit</h1>
<p>Find me in app/views/gradings/edit.html.erb</p>

app/views/gradings/index.html.erb
<table>
<tr>
<td >percent</td>
<td >importance</td>
<td >finalgrade</td>
<td >task</td>

</tr>
<% @gradings.each do |grading| %>
<tr>
<td><%= grading.percent %></td>
<td><%= grading.task.course %></td>
</tr>
<% end %>
</table>

app/views/gradings/new.html.erb
<%= form_for(@grading) do |f| %>
<div class="field">
    <p>percent of grade</p> 
    <%= f.text_field :percent%>
    </div>
    <div class="field">
    <p>importance</p> 
    <%= f.text_field :importance%>
    </div>
    <div class="field">
    <p>final grade</p> 
    <%= f.text_field :finalgrade%>
    </div>
<div class="field">
    <p>task</p> 
     <%= f.collection_select :task_id, Task.all, :id, :course%>

    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/gradings/show.html.erb
<h1>Gradings#show</h1>
<p>Find me in app/views/gradings/show.html.erb</p>

app/views/landing_pages/home.html.erb
<div id = "homepage">
<h1>Tasks</h1>
<p><%= link_to "index tasks", tasks_path%></p>
<p><%= link_to "new task", new_task_path%></p>
<h1>Subparts</h1>
<p><%= link_to "index subparts", part_lists_path%></p>
<p><%= link_to "new subpart", new_part_list_path%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.css">
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application' %>

</head>
<body>
<header class="navbar navbar-fixed-top bs-docs-nav" role="banner">
<nav id ="nav"class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Workstagram</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/.">Home</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tasks<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/tasks">View all</a></li>
          <li><a href="/tasks/new">Create new</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Subparts<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/part_lists">View all</a></li>
          <li><a href="/part_lists/new">Create new</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
</header>
</br>

<div id="user-widget">
  </br>
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to image_tag("facebook_login_button.png", :border => 0), "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>

<%= yield %> 

</body>
</html>

app/views/notifications/new_task.text.erb
<%= @greeting %>, you just created a new task! Check it out, and maybe add some parts to it <%= 
task_url(@id)%>

app/views/part_lists/edit.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
</head>
<h1 id="title1">Edit a Subpart</h1>
<a id = "unhide1">Click to hide title</a>

<%= form_for(@part_list) do |f| %>
<div class="field">
    <p>part</p> 
     <%= f.text_field :title%>
</div>
<div class="field">
    <p>complete?</p> 
     <%= f.check_box :complete%>
</div>
<div class="field">
    <p>task</p> 
    <% if current_user %>
    	<%= f.collection_select :task_id, Task.where(user_id: current_user), :id, :course %>
    <%else %>
    	<%= f.collection_select :task_id, Task.all, :id, :course %>
   	<% end %>
</div>
<div class="field">
    <p>priority</p>
    <%= f.select(:priority, options_for_select([['high', 'high'], ['medium', 'medium'], ['low', 'low']], 3)) %>
</div>
<div class="actions">
      <%= f.submit :class => "btn btn-lg btn-primary"%>
</div>
<% end %>

app/views/part_lists/index.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
</head>
<body>
</br>
<div class="container">
<h1 id="title1">Subparts</h1>
<a id = "unhide1">Click to hide title</a>
<table class = "table table-borderless" id ="tbl-tasks"> 
	<tr>
		<td id="wrk">Title</td>
		<td id="wrk">Complete?</td>
		<td id="wrk">Priority</td>
		<td id="wrk">Task</td>
	</tr>
	<% if @part_lists !=[] %>
	<% @part_lists.high_priority.each do |part_list| %>
	<tr>
		<td><%= part_list.title %></td>
		<td><%= part_list.complete %></td>
		<td><%= part_list.priority %></td>
		<td><%= part_list.task.try(:course) %></td>
		<td><%= link_to "show subpart", part_list_path(part_list.id) %></td>
		<td><%= link_to "edit subpart", edit_part_list_path(part_list.id) %> </td>
		<td><%= link_to "destroy subpart", part_list,  method: :delete %> </td>

	</tr>
	<% end %>

	<% @part_lists.med_priority.each do |part_list| %>
	<tr>
		<td><%= part_list.title %></td>
		<td><%= part_list.complete %></td>
		<td><%= part_list.priority %></td>
		<td><%= part_list.task.try(:course) %></td>
		<td><%= link_to "show subpart", part_list_path(part_list.id) %></td>
		<td><%= link_to "edit subpart", edit_part_list_path(part_list.id) %> </td>
		<td><%= link_to "destroy subpart", part_list,  method: :delete %> </td>

	</tr>
	<% end %>

	<% @part_lists.low_priority.each do |part_list| %>
	<tr >
		<td><%= part_list.title %></td>
		<td><%= part_list.complete %></td>
		<td><%= part_list.priority %></td>
		<td><%= part_list.task.try(:course) %></td>
		<td><%= link_to "show subpart", part_list_path(part_list.id) %></td>
		<td><%= link_to "edit subpart", edit_part_list_path(part_list.id) %> </td>
		<td><%= link_to "destroy subpart", part_list,  method: :delete %> </td>

	</tr>
	<% end %>
	<%end%>

</table>
<p id = "message"><%= @message %> </p>
</div>
</body>

app/views/part_lists/new.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
</head>
<h1 id="title1">Create a New Subpart</h1>
<a id = "unhide1">Click to hide title</a>

<%= form_for(@part_list) do |f| %>
  <div class="field">
    <p>title</p> 
    <%= f.text_field :title%>
  </div>
  <div class="field">
    <p>complete?</p> 
    <div class="checkbox">
      <label>
    <%= f.check_box :complete%>
      </label>
  </div>
  </div>
  <div class="field">
    <p>task</p> 
    <% if current_user %>
    <%= f.collection_select :task_id, Task.where(user_id: current_user), :id, :course %>
    <%else %>
    <%= f.collection_select :task_id, Task.all, :id, :course %>
    <% end %>
  </div>
  <div class="field">
    <p>priority</p>
    <%= f.select(:priority, options_for_select([['high', 'high'], ['medium', 'medium'], ['low', 'low']], 3)) %>
  </div>
  <div class="actions">
      <%= f.submit :class => "btn btn-lg btn-primary"%>
  </div>
<% end %>

app/views/part_lists/show.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
</head>
<h1 id="title1">Current Subpart</h1>
<a id = "unhide1">Click to hide title</a>

<div id = "show-tsk">
	<div id = "show-contents">

	<h1><%= @part_list.title %></h2>
	<p><%= @part_list.complete %></p>
	<p><%= @part_list.priority %></p>
	<p><%= @part_list.task.try(:course)%></p>
</div>
</div>

app/views/tasks/edit.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
</head>
<h1 id="title">Edit Task</h1>
<a id = "unhide">Click to hide title</a>

<div class="task-frm">
<%= semantic_form_for @task do |f| %> 
<%= f.inputs :course, :work, :dueday , :email %>
<div id = "slt"><%= f.input :user_id ,  :as => :select, :collection => User.all, :include_blank => false %></div>
</br>
<%= f.submit :class => "btn btn-lg btn-primary" %> 

<% end %> 
</div>

app/views/tasks/index.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
</head>
</br>

<div class="container">
  <h1 id="title">Upcoming Tasks</h1>
  <a id = "unhide">Click to hide title</a>
<table class = "table table-borderless" id ="tbl-tasks"> 
  <tr> 
   <td id = "crs"><b>Course</td> 
   <td id = "wrk"><b>Work</td> 
   <td id = "due"><b>Due Day</td> 
  </tr> 
  <% @tasks.each do |task| %> 
  <tr> 
   <td><%= task.course %></td> 
   <td><%= task.work %></td> 
   <td><%= task.dueday %></td> 
   <td><%= link_to "show task", task_path(task.id) %></td>
   <td><%= link_to "edit task", edit_task_path(task.id) %></td>
   <td><%= link_to "destroy task", task, confirm: "Are you sure you want to destroy this task?", method: :delete %> </td>
  </tr> 
  <% end %> 
</table> 
</div>

app/views/tasks/new.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
</head>

<h1 id="title">Create a New Task</h1>
<a id = "unhide">Click to hide title</a>

<div class="task-frm">
<%= semantic_form_for @task do |f| %> 
<%= f.inputs :course, :work, :dueday , :email %>
<div id = "slt"><%= f.input :user_id ,  :as => :select, :collection => User.all, :include_blank => false %></div>
</br>
<%= f.submit :class => "btn btn-lg btn-primary" %> 

<% end %> 
</div>

app/views/tasks/show.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Rum+Raisin' rel='stylesheet' type='text/css'>
</head>
<h1 id="title">Show Task</h1>
<a id = "unhide">Click to hide title</a>

<div id ="show-tsk">
	<div id="show-contents">
	<h1><%= @task.course %></h1>
	<p><%= @task.work %></p>
	<p><%= @task.dueday %></p>
	<p><%= @task.email %></p>
	<p><%= @name%></p>
</div>
</div>